### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by plamenradev** [miken32/NetworkRules#1]
I have an issue with Laravel 9, it throws an error:
`Trait "Illuminate\Translation\CreatesPotentiallyTranslatedStrings" not found`
As far as I see - the trait is available only on Laravel 10.

Thank you!

**Comment by miken32** [comment]
Hmm I'm not even using that trait, it's from an earlier bit of code I was playing with. I pushed some changes out; I don't have a 9.0 app to fully test with, but all the automated tests now pass with Laravel 9 and 10.

**Comment by miken32** [comment]
Assuming this is working for you now.

**Comment by jonnott** [comment]
Is this neady for a 1.0 release yet @miken32 ?

**Comment by miken32** [comment]
@jonnott  Sure, why not?
